[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[[language]]
name = "json"
language-servers = ["biome"]
auto-format = true

[[language]]
name = "jsonc"
language-servers = ["biome"]
auto-format = true

[[language]]
name = "typescript"
# Use Biome for formatting and the typescript-language-server for other LSP features
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  "biome"
]
auto-format = true
# Ensure Helix detects the project root correctly
roots = ["biome.json", "biome.jsonc", "package.json"]
